-- MySQL Script generated by MySQL Workbench
-- Mon Mar 30 22:01:27 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TipoHabitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoHabitacion` (
  `idTipoHabitacion` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(75) NOT NULL,
  `Precio` INT NOT NULL,
  `Descuento` DECIMAL NOT NULL,
  `Descripción` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`idTipoHabitacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Calificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Calificacion` (
  `idCalificacion` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCalificacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Habitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Habitacion` (
  `idHabitacion` INT NOT NULL,
  `Estado` VARCHAR(45) NOT NULL,
  `TipoHabitacion_idTipoHabitacion` INT NOT NULL,
  `Calificacion_idCalificacion` INT NOT NULL,
  PRIMARY KEY (`idHabitacion`),
  INDEX `fk_Habitacion_TipoHabitacion_idx` (`TipoHabitacion_idTipoHabitacion` ASC) VISIBLE,
  INDEX `fk_Habitacion_Calificacion1_idx` (`Calificacion_idCalificacion` ASC) VISIBLE,
  CONSTRAINT `fk_Habitacion_TipoHabitacion`
    FOREIGN KEY (`TipoHabitacion_idTipoHabitacion`)
    REFERENCES `mydb`.`TipoHabitacion` (`idTipoHabitacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Habitacion_Calificacion1`
    FOREIGN KEY (`Calificacion_idCalificacion`)
    REFERENCES `mydb`.`Calificacion` (`idCalificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoCliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoCliente` (
  `idTipoCliente` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`idTipoCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `Nombre` VARCHAR(75) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `TipoCliente_idTipoCliente` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_Cliente_TipoCliente1_idx` (`TipoCliente_idTipoCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_TipoCliente1`
    FOREIGN KEY (`TipoCliente_idTipoCliente`)
    REFERENCES `mydb`.`TipoCliente` (`idTipoCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ganancias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ganancias` (
  `idGanancias` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  `CantRes` INT NOT NULL,
  `Total` INT NOT NULL,
  PRIMARY KEY (`idGanancias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reserva` (
  `idReserva` INT NOT NULL AUTO_INCREMENT,
  `NumNoches` INT NOT NULL,
  `FechReserva` DATE NOT NULL,
  `Habitacion_idHabitacion` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Ganancias_idGanancias` INT NOT NULL,
  PRIMARY KEY (`idReserva`),
  INDEX `fk_Reserva_Habitacion1_idx` (`Habitacion_idHabitacion` ASC) VISIBLE,
  INDEX `fk_Reserva_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Reserva_Ganancias1_idx` (`Ganancias_idGanancias` ASC) VISIBLE,
  CONSTRAINT `fk_Reserva_Habitacion1`
    FOREIGN KEY (`Habitacion_idHabitacion`)
    REFERENCES `mydb`.`Habitacion` (`idHabitacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_Ganancias1`
    FOREIGN KEY (`Ganancias_idGanancias`)
    REFERENCES `mydb`.`Ganancias` (`idGanancias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FotosHabitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FotosHabitacion` (
  `idFotosHabitacion` INT NOT NULL,
  `Fotos` VARBINARY(65535) NULL,
  `TipoHabitacion_idTipoHabitacion` INT NOT NULL,
  PRIMARY KEY (`idFotosHabitacion`),
  INDEX `fk_FotosHabitacion_TipoHabitacion1_idx` (`TipoHabitacion_idTipoHabitacion` ASC) VISIBLE,
  CONSTRAINT `fk_FotosHabitacion_TipoHabitacion1`
    FOREIGN KEY (`TipoHabitacion_idTipoHabitacion`)
    REFERENCES `mydb`.`TipoHabitacion` (`idTipoHabitacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ClienteCalificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ClienteCalificacion` (
  `idClienteCalificacion` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Calificacion_idCalificacion` INT NOT NULL,
  PRIMARY KEY (`idClienteCalificacion`),
  INDEX `fk_ClienteCalificacion_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_ClienteCalificacion_Calificacion1_idx` (`Calificacion_idCalificacion` ASC) VISIBLE,
  CONSTRAINT `fk_ClienteCalificacion_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ClienteCalificacion_Calificacion1`
    FOREIGN KEY (`Calificacion_idCalificacion`)
    REFERENCES `mydb`.`Calificacion` (`idCalificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
