-- MySQL Script generated by MySQL Workbench
-- Mon Jun 15 18:26:54 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema emprosa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema emprosa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `emprosa` DEFAULT CHARACTER SET utf8 ;
USE `emprosa` ;

-- -----------------------------------------------------
-- Table `emprosa`.`Sepa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emprosa`.`Sepa` (
  `ID_Sepa` INT NOT NULL AUTO_INCREMENT,
  `Estado` VARCHAR(15) NOT NULL,
  `Nombre` VARCHAR(25) NOT NULL,
  `Dias_PCos` INT NOT NULL,
  `Dias_SCos` INT NOT NULL,
  PRIMARY KEY (`ID_Sepa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emprosa`.`Balde`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emprosa`.`Balde` (
  `Codigo_QR` VARCHAR(12) NOT NULL,
  `Estado` VARCHAR(15) NOT NULL,
  `Sepa_ID_Sepa` INT NULL,
  PRIMARY KEY (`Codigo_QR`),
  INDEX `fk_Balde_Sepa1_idx` (`Sepa_ID_Sepa` ASC),
  CONSTRAINT `fk_Balde_Sepa1`
    FOREIGN KEY (`Sepa_ID_Sepa`)
    REFERENCES `emprosa`.`Sepa` (`ID_Sepa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emprosa`.`Lote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emprosa`.`Lote` (
  `ID_Lote` INT NOT NULL AUTO_INCREMENT,
  `Estado` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`ID_Lote`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emprosa`.`Trabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emprosa`.`Trabajador` (
  `ID_Trabajador` INT NOT NULL AUTO_INCREMENT,
  `Run` VARCHAR(10) NOT NULL,
  `Estado` VARCHAR(25) NOT NULL,
  `Nombre` VARCHAR(25) NOT NULL,
  `Apellido` VARCHAR(25) NOT NULL,
  `Telefono` VARCHAR(14) NULL,
  `Gmail` VARCHAR(25) NULL,
  `Password` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`ID_Trabajador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emprosa`.`JefeCalidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emprosa`.`JefeCalidad` (
  `ID_JefeCalidad` INT NOT NULL,
  `Run` VARCHAR(10) NOT NULL,
  `Nombre` VARCHAR(25) NOT NULL,
  `Apellido` VARCHAR(25) NOT NULL,
  `Password` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`ID_JefeCalidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emprosa`.`JefeProduccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emprosa`.`JefeProduccion` (
  `ID_JefeProduccion` INT NOT NULL AUTO_INCREMENT,
  `Run` VARCHAR(10) NOT NULL,
  `Nombre` VARCHAR(25) NOT NULL,
  `Apellido` VARCHAR(25) NOT NULL,
  `Telefono` VARCHAR(14) NULL,
  `Gmail` VARCHAR(25) NULL,
  `Password` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`ID_JefeProduccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emprosa`.`Inspeccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emprosa`.`Inspeccion` (
  `ID_Inspeccion` INT NOT NULL AUTO_INCREMENT,
  `N_Inspeccion` INT NOT NULL,
  `Fecha_Ins` DATE NOT NULL,
  `Fecha_RIns` DATE NULL,
  `Estado_Ins` VARCHAR(20) NOT NULL,
  `Resultado_Ins` VARCHAR(20) NULL,
  `Comentario` VARCHAR(100) NULL,
  `Balde_Codigo_QR` VARCHAR(12) NOT NULL,
  `JefeProduccion_ID_JefeProduccion` INT NOT NULL,
  PRIMARY KEY (`ID_Inspeccion`),
  INDEX `fk_Inspeccion_Balde1_idx` (`Balde_Codigo_QR` ASC),
  INDEX `fk_Inspeccion_JefeProduccion1_idx` (`JefeProduccion_ID_JefeProduccion` ASC),
  CONSTRAINT `fk_Inspeccion_Balde1`
    FOREIGN KEY (`Balde_Codigo_QR`)
    REFERENCES `emprosa`.`Balde` (`Codigo_QR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inspeccion_JefeProduccion1`
    FOREIGN KEY (`JefeProduccion_ID_JefeProduccion`)
    REFERENCES `emprosa`.`JefeProduccion` (`ID_JefeProduccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emprosa`.`Cosecha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emprosa`.`Cosecha` (
  `ID_Cosecha` INT NOT NULL AUTO_INCREMENT,
  `N_Cos` INT NOT NULL,
  `Fecha_Cos` DATE NOT NULL,
  `Fecha_RCos` DATE NULL,
  `Estado_Cos` VARCHAR(20) NOT NULL,
  `Kgs_Rend` DOUBLE NULL,
  `Trabajador_ID_Trabajador` INT NOT NULL,
  `Balde_Codigo_QR` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`ID_Cosecha`),
  INDEX `fk_Cosecha_Trabajador1_idx` (`Trabajador_ID_Trabajador` ASC),
  INDEX `fk_Cosecha_Balde1_idx` (`Balde_Codigo_QR` ASC),
  CONSTRAINT `fk_Cosecha_Trabajador1`
    FOREIGN KEY (`Trabajador_ID_Trabajador`)
    REFERENCES `emprosa`.`Trabajador` (`ID_Trabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cosecha_Balde1`
    FOREIGN KEY (`Balde_Codigo_QR`)
    REFERENCES `emprosa`.`Balde` (`Codigo_QR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emprosa`.`Siembra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emprosa`.`Siembra` (
  `ID_siembra` INT NOT NULL,
  `Fecha_Siem` VARCHAR(45) NOT NULL,
  `Trabajador_ID_Trabajador` INT NOT NULL,
  `Balde_Codigo_QR` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`ID_siembra`),
  INDEX `fk_Siembra_Trabajador1_idx` (`Trabajador_ID_Trabajador` ASC),
  INDEX `fk_Siembra_Balde1_idx` (`Balde_Codigo_QR` ASC),
  CONSTRAINT `fk_Siembra_Trabajador1`
    FOREIGN KEY (`Trabajador_ID_Trabajador`)
    REFERENCES `emprosa`.`Trabajador` (`ID_Trabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Siembra_Balde1`
    FOREIGN KEY (`Balde_Codigo_QR`)
    REFERENCES `emprosa`.`Balde` (`Codigo_QR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emprosa`.`Lote_Balde`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emprosa`.`Lote_Balde` (
  `ID_LoteBalde` INT NOT NULL,
  `Lote_ID_Lote` INT NOT NULL,
  `Balde_Codigo_QR` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`ID_LoteBalde`),
  INDEX `fk_Lote_Balde_Lote1_idx` (`Lote_ID_Lote` ASC),
  INDEX `fk_Lote_Balde_Balde1_idx` (`Balde_Codigo_QR` ASC),
  CONSTRAINT `fk_Lote_Balde_Lote1`
    FOREIGN KEY (`Lote_ID_Lote`)
    REFERENCES `emprosa`.`Lote` (`ID_Lote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lote_Balde_Balde1`
    FOREIGN KEY (`Balde_Codigo_QR`)
    REFERENCES `emprosa`.`Balde` (`Codigo_QR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
